version: '3'
services:
  # Web フロント
  wkhtmltopdf:
    build:
      context: ./wkhtmltopdf
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
        - no_proxy=${no_proxy}
    # env_file: /etc/docker/.env
  
    container_name: wkhtmltopdf
    volumes:
    - "./:/tmp/"
    working_dir: /tmp/
